name: Test build

on:
  push:
    branches:
      - "**" # Run on all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies
      - name: Install dependencies
        run: bun i

      - name: setup test deploy
        run: bun deploy-dev:setup
